### ISSUE TITLE
Make tests

### ISSUE THREAD

**Issue by josueBarretogit** [josueBarretogit/manga-tui#1]
I have no idea how to test the App itself, I can start making test for the filter to make sure they work but other than that i dont know

**Comment by josueBarretogit** [comment]
Also integrate workflows

**Comment by meisimo** [comment]
If you started developing everithing without unit or integration tests could be frustrating to start now with those "low level" tests, that doesn't ensure that your app does what is suppose to do. So one thing that you could try is to make some E2E tests as regretion tests, I mean, to make sure that what works is still working after any change.  Taking the core features and start by making some happy path tests of them.

The only anoying thing with this particular kind of App is how to mock the external APIs without touching too much code (or any code ideally). In that case I think trying `mockito` could help to mock the API responses or a less intrusive  option could be an external mock service as `hoverfly` that is not too hard to configure.

**Comment by josueBarretogit** [comment]
Thanks for the suggestions, One thing I'm struggling with right now is making tests, specially those that require something "external" like functions that make API calls and testing a function that make directories, how can I write tests for those? I'll be investigating more about this

**Comment by josueBarretogit** [comment]
closed in #29
