### ISSUE TITLE
[Feature Request]  Ability to Read Local Manga Files

### ISSUE THREAD

**Issue by nirmaleeswar30** [josueBarretogit/manga-tui#13]
Currently, manga-tui primarily focuses on fetching manga from online sources. Users would benefit greatly from the ability to import and read manga that has already been downloaded to their local storage. This feature would allow users to manage and access their existing manga collection within the manga-tui interface. Thank You!!

**Comment by josueBarretogit** [comment]
Hi thanks for taking your time opening this issue, what you are proposing sounds like a different application, the "vision" of this project is get manga either by downloading it or if your terminal supports it read it directly, in fact I'm planning on adding more manga providers like [mangapill](https://mangapill.com/) (currently only mangadex is used), improve downloading manga, see #11  and #10 and also integrate tracking functionality via Anilist or Myanimelist. I took inspiration from [mangadesk](https://github.com/darylhjd/mangadesk) and was like: what if you make this application and also take advantage of terminal emulators that support image display, that would be great for people who want to search manga

Btw sorry for any inconveniences you may have experienced with #12 I just assumed the image display worked fine for that terminal

Hope you understand 🙏

**Comment by nirmaleeswar30** [comment]
Hi josueBarretogit,

Thank you for sharing the vision of your project with me. I completely understand the direction you're aiming for. Expanding the manga providers and improving downloading functionality, as mentioned in [#10](https://github.com/josueBarretogit/manga-tui/issues/10) and [#11](https://github.com/josueBarretogit/manga-tui/pull/11), will definitely enhance the user experience.

Regarding [#12](https://github.com/josueBarretogit/manga-tui/issues/12), no worries at all! I appreciate your efforts in trying to make the application work across different terminal environments, and I’m sure the community will benefit from these enhancements. Looking forward to seeing the future updates!

Thanks for your hard work, and no inconvenience at all. Keep up the great work! 🙏
