### ISSUE TITLE
Deterministic builds

### ISSUE THREAD

**Issue by RatCornu** [josueBarretogit/manga-tui#17]
Hello! This project is very cool and I and think a great think to add and that is not that much complicated to set up nowadays is deterministic builds. This would allow new contributors to be sure of how to contribute to the project. I think it would great to have at least three files :

- `rust-toolchain.toml` to declare the version of the rust compiler
- `rustfmt.toml` to declare the options to give when running `cargo fmt` (which would allow for example to do a `cargo fmt --check` in the "test" github workflow)
- `flake.nix` for the nix users

I can make a PR if you're interested! I would just need the version of the compiler you use to setup `rust-toolchain.toml`

**Comment by ElrohirGT** [comment]
I second the `flake.nix`! It would be great to have one for this project.

**Comment by josueBarretogit** [comment]
Hi I'm glad you found this project interesting! I'm still learning as I continue working on this project so any help is very much appreciated, for the `rust-toolchain.toml` I'm using the `stable` version

**Comment by josueBarretogit** [comment]
Closed in #19
