### ISSUE TITLE
no way to search by excluding tags

### ISSUE THREAD

**Issue by db48x** [josueBarretogit/manga-tui#2]
I took a look through the source and noticed that there is no way to do a search while excluding tags. Assuming the API supports it (I didn’t check), that seems like an obvious thing to add.

**Comment by db48x** [comment]
Also, I find that I am curious to know if you will change your FilterList to have more states beyond just a simple boolean, or if you will put two of them in the UI, one for included tags and the other for excluded. That sounds simpler, but permits illogical selections (including and excluding the same tag).

And then there’s the problem of the IntoParams trait for Tags. It has a hard–coded field name, so if the API uses a different field name for exclusions (seems probable given what that field name is) then you have an interesting problem. Will you do `struct ExcludedTags(Vec<String>)` or `struct Tags{fieldname: String, tags: Vec<String>}`?

**Comment by josueBarretogit** [comment]
Hi man thanks for taking your time to read the source code, the reason there is no way to exclude tags is because I personally never do that (yes I know very selfish reason), as a result I did not write the code so that it supports that kind of filtering and yeah in order to implement that functionality the `Tags` struct needs to be better designed

**Comment by josueBarretogit** [comment]
The mangadex API supports excluding tags, instead of `includedTags[]` is `excludedTags[]`

**Comment by db48x** [comment]
Selfish or not, you gotta start somewhere. :)

**Comment by josueBarretogit** [comment]
To introduce this functionality, if the user inputs `<s>` it includes the tag and the tag gets highlighted in green, if the user inputs `<e>` it excludes the tag and the tag gets highlighted in red

**Comment by db48x** [comment]
Nice, you didn’t do it how I guessed :)
