### ISSUE TITLE
Download feature is not working properly

### ISSUE THREAD

**Issue by Skinnyytallboy** [josueBarretogit/manga-tui#30]
So firstly the manga-tui isn't launching without internet, it should check for downloaded stuff and then either display the already downloaded manga or show an error incase of no internet and manga.
Secondly even if you download, next time when you run the program, it will start running the manga on the internet and doesn't load the downloaded one, even it shows the downloaded symbol representing that you downloaded this but it's still running live over the internet.

Eventhough the downloaded mangas are present in the file system

**Comment by josueBarretogit** [comment]
Hi thanks for using manga-tui I hope you like it!
If you could download manga then the download feature is working as expected, now if you couldn't download certain manga or a chapter or you got some error please let me know.

Reading mangas locally is not and won't be supported, see #13, basically I think it is better to have a different application that focuses on that task of reading files locally, it doesn't need to be tied to manga exclusively, it could be a comic book archive(cbz), epub reader and image viewer for anything really, not just manga and it could even support more file formats, see for example [tdf a pdf viewer](https://github.com/itsjunetime/tdf)

**Comment by Banh-Canh** [comment]
> Hi thanks for using manga-tui I hope you like it! If you could download manga then the download feature is working as expected, now if you couldn't download certain manga or a chapter or you got some error please let me know.
> 
> Reading mangas locally is not and won't be supported, see #13, basically I think it is better to have a different application that focuses on that task of reading files locally, it doesn't need to be tied to manga exclusively, it could be a comic book archive(cbz), epub reader and image viewer for anything really, not just manga and it could even support more file formats, see for example [tdf a pdf viewer](https://github.com/itsjunetime/tdf)

Hey, love it as it is as well :)
I think we all meant for it to be able to make use of an "offline mode" where everything downloaded by manga-tui is actually used and read instead of redownloading a chapter ! But I'm also very happy with it now, it looks so neato

**Comment by josueBarretogit** [comment]
closing this issue hopefully a new project is born from this
