### ISSUE TITLE
Option to mark on which page the manga has been left to pick up next time (Bookmark)

### ISSUE THREAD

**Issue by itslu666** [josueBarretogit/manga-tui#35]

**Comment by josueBarretogit** [comment]
Sounds like a nice feature to have, I wonder how exactly would you want this to work? does the user bookmark the chapter they want to read later or does it default to the latest one read?

**Comment by itslu666** [comment]
I think both would be a good option, being able to set an autobookmarking option to true in the settings or if its on false you can manually do it by pressing a button on the page you wanna save.

**Comment by josueBarretogit** [comment]
closed in #50
