### ISSUE TITLE
StatefulImage error during build

### ISSUE THREAD

**Issue by Nic-Vladimir** [josueBarretogit/manga-tui#5]
I tried installing using  `cargo install manga-tui`
I'm on Arch Linux, kitty term, just did a Syu.
This is the error I get during installation:

> error[E0277]: the trait bound `StatefulImage: ratatui::prelude::StatefulWidget` is not satisfied
>   --> /home/vladimir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/manga-tui-0.1.0/src/view/widgets/home.rs:43:40
>    |
> 43 |                 StatefulWidget::render(cover, area, buf, image_state)
>    |                 ---------------------- ^^^^^ **the trait `ratatui::prelude::StatefulWidget` is not implemented for `StatefulImage`**
>    |                 |
>    |                 required by a bound introduced by this call
>    |
>    = help: the following other types implement trait `ratatui::prelude::StatefulWidget`:
>              &Table<'_>
>              &ratatui::widgets::List<'_>
>              ChaptersListWidget
>              HistoryWidget
>              PagesList
>              PopularMangaCarrousel
>              RecentlyAddedCarrousel
>              Scrollbar<'a>
>            and 5 others

**Comment by josueBarretogit** [comment]
I think it's an issue with the versions of the crates, try running `cargo install manga-tui --locked`

**Comment by Nic-Vladimir** [comment]
> I think it's an issue with the versions of the crates, try running `cargo install manga-tui --locked`

Thanks! That worked! Cool project btw!

**Comment by donovanglover** [comment]
Would it be possible to fix this without using a git dependency for `ratatui-image`? Is this because of a breaking change in ratatui 0.28.0?

**Comment by josueBarretogit** [comment]
I haven't updated because I use other dependencies that depend on `rataui 0.27.0`, I just checked and It seems this dependencies have updated to use `rataui 0.28.0`, I'll be updating and see if there is no issue in the build

**Comment by ElrohirGT** [comment]
I was having the same issue and can confirm that `cargo install manga-tui --locked` fixed it!

It would be nice that we could update the project by typing just `cargo install` with no additional flags but still, great work! I'm definitively using this reader almost daily now.

**Comment by josueBarretogit** [comment]
@donovanglover I removed the git dependency do I have to release a new version with this change?

**Comment by donovanglover** [comment]
That'd be great, thank you!

**Comment by josueBarretogit** [comment]
closed in #12

**Comment by josueBarretogit** [comment]
closed in #12
