### ISSUE TITLE
Failing to build in Nix due to tests

### ISSUE THREAD

**Issue by youwen5** [josueBarretogit/manga-tui#57]
Hi, the test `show_error_when_searching_manga` fails when building with `nix build github:josueBarretogit/manga-tui` (using the project's own `flake.nix`). Additionally, the test `it_sends_event_chapter_bookmarked_failed_to_fetch` also fails when building inside `nixpkgs`.

I managed to package the update downstream at <https://github.com/NixOS/nixpkgs/pull/353060> by fixing/removing the failing tests using patches. I am not familiar enough with the codebase to know why they fail in the Nix build sandbox so I am not sure what the best way to fix these tests is.

I opened #56 to fix the project's own failing `flake.nix`, but it doesn't fix the `it_sends_event_chapter_bookmarked_failed_to_fetch` test failing in `nixpkgs` since I'm not quite sure how to do that. Worst case, we can just leave that patch in `nixpkgs` removing the test at build-time to stop it from killing the build since the test passes successfully when not building with Nix.

**Comment by josueBarretogit** [comment]
Im never getting the test right 😭
![sisiphus](https://github.com/user-attachments/assets/8063933d-14ac-4625-ad7e-6ace5c322cfc)

**Comment by josueBarretogit** [comment]
closed in #56
